### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by code004Accepted** [tosdr/CrispCMS#66]
exception_cae2baee-7adb-f92f-509c-4c06ea7084c4

**Comment by JustinBack** [comment]
Related to #65 

Redis somehow put itself into readonly mode

```
READONLY You can't write against a read only slave.

https://tosdr.org/favicon.ico
```

```
#0 DOCROOT\pixelcatproductions\class\RateLimit\RedisRateLimiter.php(70): Redis->incr()
#1 DOCROOT\pixelcatproductions\class\RateLimit\RedisRateLimiter.php(47): RateLimit\RedisRateLimiter->updateCounter()
#2 DOCROOT\pixelcatproductions\crisp.php(200): RateLimit\RedisRateLimiter->limitSilently()
#3 DOCROOT\index.php(20): require_once('DOCROOT')
#4 {main}
```

This has been fixed.
